/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.awt.Toolkit;

/**
 *
 * @author prueb
 */
public class FrmCreditos extends javax.swing.JFrame {

    /**
     * Creates new form FrmCreditos
     */
    public FrmCreditos() {
        initComponents();
        setSize(840, 531);
        setResizable(false);
        setLocationRelativeTo(null);
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/imagenesVentanas/logo_coolscooter.png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelCreditos = new javax.swing.JPanel();
        lblcreditos1 = new javax.swing.JLabel();
        lblcreditosTitulo = new javax.swing.JLabel();
        lblcreditosProgramadores = new javax.swing.JLabel();
        lblcreditosCPT = new javax.swing.JLabel();
        lblcreditosCQR = new javax.swing.JLabel();
        lblcreditosDiseñadores = new javax.swing.JLabel();
        lblcreditosJLI = new javax.swing.JLabel();
        lblcreditosAPC = new javax.swing.JLabel();
        lblcreditosGVS = new javax.swing.JLabel();
        lblcreditosJAS = new javax.swing.JLabel();
        lblcreditosSLA = new javax.swing.JLabel();
        lblcreditosEditores = new javax.swing.JLabel();
        btnCasaInicio = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelCreditos.setBackground(new java.awt.Color(0, 0, 0));
        panelCreditos.setPreferredSize(new java.awt.Dimension(830, 490));
        panelCreditos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblcreditos1.setFont(new java.awt.Font("Nirmala UI", 1, 24)); // NOI18N
        lblcreditos1.setForeground(new java.awt.Color(255, 255, 255));
        lblcreditos1.setText("ESTUDIANTES DE LA UNIVERSIDAD AUTÓNOMA DEL PERÚ:");
        panelCreditos.add(lblcreditos1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 790, 60));

        lblcreditosTitulo.setFont(new java.awt.Font("Nirmala UI", 1, 48)); // NOI18N
        lblcreditosTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblcreditosTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblcreditosTitulo.setText("INTEGRANTES DEL PROYECTO");
        panelCreditos.add(lblcreditosTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 30, 790, -1));

        lblcreditosProgramadores.setFont(new java.awt.Font("Nirmala UI", 1, 24)); // NOI18N
        lblcreditosProgramadores.setForeground(new java.awt.Color(255, 255, 255));
        lblcreditosProgramadores.setText("PROGRAMADORES:");
        panelCreditos.add(lblcreditosProgramadores, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, -1, -1));

        lblcreditosCPT.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 24)); // NOI18N
        lblcreditosCPT.setForeground(new java.awt.Color(255, 255, 255));
        lblcreditosCPT.setText("Palacios Tarrillo, Christian ");
        panelCreditos.add(lblcreditosCPT, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 160, -1, -1));

        lblcreditosCQR.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 24)); // NOI18N
        lblcreditosCQR.setForeground(new java.awt.Color(255, 255, 255));
        lblcreditosCQR.setText("Quispe Ramirez, Cristhian");
        panelCreditos.add(lblcreditosCQR, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 200, -1, -1));

        lblcreditosDiseñadores.setFont(new java.awt.Font("Nirmala UI", 1, 24)); // NOI18N
        lblcreditosDiseñadores.setForeground(new java.awt.Color(255, 255, 255));
        lblcreditosDiseñadores.setText("DISEÑADORES:");
        panelCreditos.add(lblcreditosDiseñadores, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, -1, -1));

        lblcreditosJLI.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 24)); // NOI18N
        lblcreditosJLI.setForeground(new java.awt.Color(255, 255, 255));
        lblcreditosJLI.setText("Luyo Infantes, José");
        panelCreditos.add(lblcreditosJLI, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 250, -1, -1));

        lblcreditosAPC.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 24)); // NOI18N
        lblcreditosAPC.setForeground(new java.awt.Color(255, 255, 255));
        lblcreditosAPC.setText("Palacios Carrillo, Albert");
        panelCreditos.add(lblcreditosAPC, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 290, -1, -1));

        lblcreditosGVS.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 24)); // NOI18N
        lblcreditosGVS.setForeground(new java.awt.Color(255, 255, 255));
        lblcreditosGVS.setText("Villavicencio Sifuentes, Gino");
        panelCreditos.add(lblcreditosGVS, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 330, -1, -1));

        lblcreditosJAS.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 24)); // NOI18N
        lblcreditosJAS.setForeground(new java.awt.Color(255, 255, 255));
        lblcreditosJAS.setText("Ascue Silva, Joel");
        panelCreditos.add(lblcreditosJAS, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 380, -1, -1));

        lblcreditosSLA.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 24)); // NOI18N
        lblcreditosSLA.setForeground(new java.awt.Color(255, 255, 255));
        lblcreditosSLA.setText("Larrea Alva, Sebastian");
        panelCreditos.add(lblcreditosSLA, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 420, -1, -1));

        lblcreditosEditores.setFont(new java.awt.Font("Nirmala UI", 1, 24)); // NOI18N
        lblcreditosEditores.setForeground(new java.awt.Color(255, 255, 255));
        lblcreditosEditores.setText("EDITORES:");
        panelCreditos.add(lblcreditosEditores, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 380, -1, -1));

        btnCasaInicio.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 16)); // NOI18N
        btnCasaInicio.setForeground(new java.awt.Color(255, 255, 255));
        btnCasaInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesLogin/imgInicio.png"))); // NOI18N
        btnCasaInicio.setText("Inicio");
        btnCasaInicio.setContentAreaFilled(false);
        btnCasaInicio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCasaInicio.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCasaInicio.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesLogin/imgInicioSelec.png"))); // NOI18N
        btnCasaInicio.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesLogin/imgInicio.png"))); // NOI18N
        btnCasaInicio.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCasaInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCasaInicioActionPerformed(evt);
            }
        });
        panelCreditos.add(btnCasaInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 360, 80, 110));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesVentanas/imgFondoCreditos.png"))); // NOI18N
        panelCreditos.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 490));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelCreditos, javax.swing.GroupLayout.DEFAULT_SIZE, 850, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelCreditos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCasaInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCasaInicioActionPerformed
        FrmInicio formInicio = new FrmInicio();
        dispose();
        formInicio.setVisible(true);
    }//GEN-LAST:event_btnCasaInicioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmCreditos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmCreditos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmCreditos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmCreditos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmCreditos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCasaInicio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblcreditos1;
    private javax.swing.JLabel lblcreditosAPC;
    private javax.swing.JLabel lblcreditosCPT;
    private javax.swing.JLabel lblcreditosCQR;
    private javax.swing.JLabel lblcreditosDiseñadores;
    private javax.swing.JLabel lblcreditosEditores;
    private javax.swing.JLabel lblcreditosGVS;
    private javax.swing.JLabel lblcreditosJAS;
    private javax.swing.JLabel lblcreditosJLI;
    private javax.swing.JLabel lblcreditosProgramadores;
    private javax.swing.JLabel lblcreditosSLA;
    private javax.swing.JLabel lblcreditosTitulo;
    private javax.swing.JPanel panelCreditos;
    // End of variables declaration//GEN-END:variables
}
