package vista;

import java.awt.Desktop;
import java.awt.Toolkit;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;

/**
 * @author prueb
 */
public class FrmInicio extends javax.swing.JFrame {

    /**
     * Creates new form FrmInicio
     */
    public FrmInicio() {
        initComponents();
        setLocationRelativeTo(null);
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/imagenesVentanas/logo_coolscooter.png")));
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelInicio = new javax.swing.JPanel();
        btnInicio = new javax.swing.JButton();
        btnCoolScooter = new javax.swing.JButton();
        btnCreditos = new javax.swing.JButton();
        lblFondoInicio = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelInicio.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnInicio.setFont(new java.awt.Font("Consolas", 3, 24)); // NOI18N
        btnInicio.setForeground(new java.awt.Color(244, 253, 251));
        btnInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesInicio/imgBotonesInicio.png"))); // NOI18N
        btnInicio.setText("Iniciar");
        btnInicio.setBorder(null);
        btnInicio.setContentAreaFilled(false);
        btnInicio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnInicio.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnInicio.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesInicio/imgBotonesInicioSelec.png"))); // NOI18N
        btnInicio.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesInicio/imgBotonesInicio.png"))); // NOI18N
        btnInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicioActionPerformed(evt);
            }
        });
        panelInicio.add(btnInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 230, 380, 40));

        btnCoolScooter.setFont(new java.awt.Font("Consolas", 3, 24)); // NOI18N
        btnCoolScooter.setForeground(new java.awt.Color(244, 253, 251));
        btnCoolScooter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesInicio/imgBotonesInicio.png"))); // NOI18N
        btnCoolScooter.setText("CoolScooter");
        btnCoolScooter.setContentAreaFilled(false);
        btnCoolScooter.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCoolScooter.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCoolScooter.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesInicio/imgBotonesInicioSelec.png"))); // NOI18N
        btnCoolScooter.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesInicio/imgBotonesInicio.png"))); // NOI18N
        btnCoolScooter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCoolScooterActionPerformed(evt);
            }
        });
        panelInicio.add(btnCoolScooter, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 280, 380, 40));

        btnCreditos.setFont(new java.awt.Font("Consolas", 3, 24)); // NOI18N
        btnCreditos.setForeground(new java.awt.Color(244, 253, 251));
        btnCreditos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesInicio/imgBotonesInicio.png"))); // NOI18N
        btnCreditos.setText("Creditos");
        btnCreditos.setContentAreaFilled(false);
        btnCreditos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCreditos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCreditos.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesInicio/imgBotonesInicioSelec.png"))); // NOI18N
        btnCreditos.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesInicio/imgBotonesInicio.png"))); // NOI18N
        btnCreditos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreditosActionPerformed(evt);
            }
        });
        panelInicio.add(btnCreditos, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 330, 380, 40));

        lblFondoInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesInicio/imgInicio.png"))); // NOI18N
        panelInicio.add(lblFondoInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelInicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelInicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioActionPerformed
        FrmLogin formLogin = new FrmLogin();
        dispose();
        formLogin.setVisible(true);
    }//GEN-LAST:event_btnInicioActionPerformed

    private void btnCreditosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreditosActionPerformed
        FrmCreditos formCredito = new FrmCreditos();
        dispose();
        formCredito.setVisible(true);
    }//GEN-LAST:event_btnCreditosActionPerformed

    private void btnCoolScooterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCoolScooterActionPerformed
        try {
            Desktop.getDesktop().browse(new URI("https://www.facebook.com/coolscooterpe/"));
        } catch (URISyntaxException ex) {
            //
        } catch (IOException ex) {
            //
        }
    }//GEN-LAST:event_btnCoolScooterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmInicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCoolScooter;
    private javax.swing.JButton btnCreditos;
    private javax.swing.JButton btnInicio;
    private javax.swing.JLabel lblFondoInicio;
    private javax.swing.JPanel panelInicio;
    // End of variables declaration//GEN-END:variables
}
