package vista;

import java.awt.Desktop;
import java.awt.Toolkit;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import modelo.ArchivoProforma;
import modelo.GestionEncabezadoTabla;
import modelo.Proforma;

/**
 * @author prueb
 */
public class FrmRepertorioDatos extends javax.swing.JFrame {

    private DefaultTableModel ClientesModelo;
    private DefaultTableModel CaracteristicasModelo;
    private DefaultTableModel CaracteristicasFisicasModelo;
    private JTableHeader tableHeaderClientes;
    private ArrayList<Proforma> datosCliente;
    private ArchivoProforma file = new ArchivoProforma();
    private String direccionPro = "Documents\\repertorioProforma.txt";
    private String user;

    public FrmRepertorioDatos(String user) {
        this.user = user;
        initComponents();
//        setResizable(false);
        iniciarTabla();
        iniciarModeloClientes();
        setLocationRelativeTo(null);
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/imagenesVentanas/logo_coolscooter.png")));
    }

    private FrmRepertorioDatos() {
    }

    public void iniciarTabla() {
        //Cambiar el diseño del encabezado de la tabla
        tableHeaderClientes = tabla.getTableHeader();
        tableHeaderClientes.setDefaultRenderer(new GestionEncabezadoTabla());
        tabla.setTableHeader(tableHeaderClientes);
        menuItemUser.setText("  " + user);
        tgbCliente.setSelected(true);
        datosCliente = file.generarArrayListCliente();
    }

    public void iniciarModeloClientes() {
        String[] columnaCliente = {"Cliente", "Telefono", "N° DNI", "Fecha de emisión"};
        ClientesModelo = new DefaultTableModel(null, columnaCliente) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        tabla.setModel(ClientesModelo);
        for (Proforma pro : datosCliente) {
            ClientesModelo.addRow(pro.getDatoCliente());
        }
    }

    public void iniciarModeloCaracteristicas() {
        String[] columnaCaracteristicas = {"Tipo vehículo", "Marca", "Modelo", "Código de producto"};
        CaracteristicasModelo = new DefaultTableModel(null, columnaCaracteristicas) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        tabla.setModel(CaracteristicasModelo);
        for (Proforma pro : datosCliente) {
            CaracteristicasModelo.addRow(pro.getCaracteristicas());
        }
    }

    public void iniciarModeloCaracteristicasFisicas() {
        // tiempo, kilometraje, velocidad, velocidad instantenea, aceleracion
        String[] columnaCaracteristicasFisicas = {"Tiempo", "Distancia", "Velocidad", "Velocidad instantenea", "Aceleración"};
        CaracteristicasFisicasModelo = new DefaultTableModel(null, columnaCaracteristicasFisicas) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        tabla.setModel(CaracteristicasFisicasModelo);
        for (Proforma pro : datosCliente) {
            CaracteristicasFisicasModelo.addRow(pro.getCaracteristicasFisicas());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btngCambioTablasModelo = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        lbltituloRepertorio = new javax.swing.JLabel();
        btnEliminarTodo = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        tgbCaracteristicasFisicas = new javax.swing.JToggleButton();
        tgbCaracteristicas = new javax.swing.JToggleButton();
        tgbCliente = new javax.swing.JToggleButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        lblFondo = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuItemUser = new javax.swing.JMenu();
        menuItemCerrarSesión = new javax.swing.JMenuItem();
        menuItemPrincipal = new javax.swing.JMenu();
        menuItemProforma = new javax.swing.JMenu();
        menuItemPagWeb = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbltituloRepertorio.setBackground(new java.awt.Color(60, 233, 229));
        lbltituloRepertorio.setFont(new java.awt.Font("Bahnschrift", 1, 75)); // NOI18N
        lbltituloRepertorio.setForeground(new java.awt.Color(255, 255, 255));
        lbltituloRepertorio.setText("Repertorio de datos");
        jPanel1.add(lbltituloRepertorio, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 810, 90));

        btnEliminarTodo.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        btnEliminarTodo.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminarTodo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesTablaRepertorio/imgClearSelec.png"))); // NOI18N
        btnEliminarTodo.setText("Eliminar todo");
        btnEliminarTodo.setContentAreaFilled(false);
        btnEliminarTodo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEliminarTodo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEliminarTodo.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesTablaRepertorio/imgClearSelec.png"))); // NOI18N
        btnEliminarTodo.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesTablaRepertorio/imgClear.png"))); // NOI18N
        btnEliminarTodo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnEliminarTodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarTodoActionPerformed(evt);
            }
        });
        jPanel1.add(btnEliminarTodo, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 480, 130, 120));

        btnEliminar.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesTablaRepertorio/imgEliminar.png"))); // NOI18N
        btnEliminar.setText("Eliminar cliente");
        btnEliminar.setContentAreaFilled(false);
        btnEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEliminar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEliminar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        jPanel1.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(974, 320, -1, 120));

        btngCambioTablasModelo.add(tgbCaracteristicasFisicas);
        tgbCaracteristicasFisicas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesTablaRepertorio/imgCaracteristicasFisicas.png"))); // NOI18N
        tgbCaracteristicasFisicas.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesTablaRepertorio/imgCaracteristicasFisicasSelec.png"))); // NOI18N
        tgbCaracteristicasFisicas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tgbCaracteristicasFisicasActionPerformed(evt);
            }
        });
        jPanel1.add(tgbCaracteristicasFisicas, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 150, 80, 80));

        btngCambioTablasModelo.add(tgbCaracteristicas);
        tgbCaracteristicas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesTablaRepertorio/imgScooter.png"))); // NOI18N
        tgbCaracteristicas.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesTablaRepertorio/imgScooterSelec.png"))); // NOI18N
        tgbCaracteristicas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tgbCaracteristicasActionPerformed(evt);
            }
        });
        jPanel1.add(tgbCaracteristicas, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, 80, 80));

        btngCambioTablasModelo.add(tgbCliente);
        tgbCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesTablaRepertorio/imgCliente.png"))); // NOI18N
        tgbCliente.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesTablaRepertorio/imgClienteSelec.png"))); // NOI18N
        tgbCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tgbClienteActionPerformed(evt);
            }
        });
        jPanel1.add(tgbCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, 80, 80));

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabla.setAlignmentX(5.0F);
        tabla.setAlignmentY(5.0F);
        tabla.setFocusable(false);
        tabla.setRowHeight(40);
        tabla.setSelectionBackground(new java.awt.Color(170, 207, 255));
        tabla.setSelectionForeground(new java.awt.Color(0, 0, 0));
        tabla.setShowHorizontalLines(true);
        tabla.setShowVerticalLines(true);
        tabla.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tabla);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, 900, 400));

        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesTablaRepertorio/imgfondoAzulOscuro.jpg"))); // NOI18N
        jPanel1.add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1118, 700));

        jMenuBar1.setBackground(new java.awt.Color(84, 156, 159));
        jMenuBar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuBar1.setEnabled(false);
        jMenuBar1.setFocusCycleRoot(true);
        jMenuBar1.setFocusable(false);
        jMenuBar1.setOpaque(true);

        menuItemUser.setBackground(new java.awt.Color(84, 156, 159));
        menuItemUser.setForeground(new java.awt.Color(255, 255, 255));
        menuItemUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesVentanas/imgUser.png"))); // NOI18N
        menuItemUser.setText("Usuario");
        menuItemUser.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuItemUser.setFocusPainted(true);
        menuItemUser.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        menuItemUser.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        menuItemUser.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        menuItemUser.setMargin(new java.awt.Insets(3, 6, 3, 30));
        menuItemUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuItemUserMouseClicked(evt);
            }
        });
        menuItemUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemUserActionPerformed(evt);
            }
        });

        menuItemCerrarSesión.setBackground(new java.awt.Color(84, 156, 159));
        menuItemCerrarSesión.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        menuItemCerrarSesión.setForeground(new java.awt.Color(255, 255, 255));
        menuItemCerrarSesión.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesVentanas/imgCerrarSesion.png"))); // NOI18N
        menuItemCerrarSesión.setText("Cerrar sesión");
        menuItemCerrarSesión.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuItemCerrarSesión.setFocusCycleRoot(true);
        menuItemCerrarSesión.setFocusable(true);
        menuItemCerrarSesión.setOpaque(true);
        menuItemCerrarSesión.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuItemCerrarSesiónMouseClicked(evt);
            }
        });
        menuItemCerrarSesión.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemCerrarSesiónActionPerformed(evt);
            }
        });
        menuItemUser.add(menuItemCerrarSesión);

        jMenuBar1.add(menuItemUser);

        menuItemPrincipal.setForeground(new java.awt.Color(255, 255, 255));
        menuItemPrincipal.setText("Principal");
        menuItemPrincipal.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        menuItemPrincipal.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        menuItemPrincipal.setMargin(new java.awt.Insets(3, 30, 3, 30));
        menuItemPrincipal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuItemPrincipalMouseClicked(evt);
            }
        });
        menuItemPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemPrincipalActionPerformed(evt);
            }
        });
        jMenuBar1.add(menuItemPrincipal);

        menuItemProforma.setForeground(new java.awt.Color(255, 255, 255));
        menuItemProforma.setText("Proforma");
        menuItemProforma.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        menuItemProforma.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        menuItemProforma.setMargin(new java.awt.Insets(3, 30, 3, 30));
        menuItemProforma.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuItemProformaMouseClicked(evt);
            }
        });
        menuItemProforma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemProformaActionPerformed(evt);
            }
        });
        jMenuBar1.add(menuItemProforma);

        menuItemPagWeb.setForeground(new java.awt.Color(255, 255, 255));
        menuItemPagWeb.setText("Ver pagina web");
        menuItemPagWeb.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        menuItemPagWeb.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        menuItemPagWeb.setMargin(new java.awt.Insets(3, 30, 3, 30));
        menuItemPagWeb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuItemPagWebMouseClicked(evt);
            }
        });
        jMenuBar1.add(menuItemPagWeb);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuItemCerrarSesiónMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuItemCerrarSesiónMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_menuItemCerrarSesiónMouseClicked

    private void menuItemCerrarSesiónActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemCerrarSesiónActionPerformed
        FrmLogin formLogin = new FrmLogin();
        formLogin.setVisible(true);
        dispose();
    }//GEN-LAST:event_menuItemCerrarSesiónActionPerformed

    private void menuItemUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuItemUserMouseClicked

    }//GEN-LAST:event_menuItemUserMouseClicked

    private void menuItemUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemUserActionPerformed

    }//GEN-LAST:event_menuItemUserActionPerformed

    private void tgbCaracteristicasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tgbCaracteristicasActionPerformed
        iniciarModeloCaracteristicas();
    }//GEN-LAST:event_tgbCaracteristicasActionPerformed

    private void tgbClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tgbClienteActionPerformed
        iniciarModeloClientes();
    }//GEN-LAST:event_tgbClienteActionPerformed

    private void tgbCaracteristicasFisicasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tgbCaracteristicasFisicasActionPerformed
        iniciarModeloCaracteristicasFisicas();
    }//GEN-LAST:event_tgbCaracteristicasFisicasActionPerformed

    private void menuItemPrincipalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuItemPrincipalMouseClicked
        FrmPrincipal formPrincipal = new FrmPrincipal("tiempo", this.user);
        formPrincipal.setVisible(true);
        dispose();
    }//GEN-LAST:event_menuItemPrincipalMouseClicked

    private void menuItemPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemPrincipalActionPerformed

    }//GEN-LAST:event_menuItemPrincipalActionPerformed

    private void menuItemProformaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuItemProformaMouseClicked
        float[] caracteristicasMag = new float[5];
        for (int i = 0; i < caracteristicasMag.length; i++) {
            caracteristicasMag[i] = 0f;
        }
        FrmGeneradorProforma formGenProforma = new FrmGeneradorProforma(caracteristicasMag, this.user);
        formGenProforma.setVisible(true);
        dispose();
    }//GEN-LAST:event_menuItemProformaMouseClicked

    private void menuItemProformaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemProformaActionPerformed

    }//GEN-LAST:event_menuItemProformaActionPerformed

    private void menuItemPagWebMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuItemPagWebMouseClicked
        try {
            Desktop.getDesktop().browse(new URI("https://www.youroutlet.pe/coolscooter"));
        } catch (URISyntaxException ex) {
            //
        } catch (IOException ex) {
            //
        }
    }//GEN-LAST:event_menuItemPagWebMouseClicked

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        int celdaSelec = tabla.getSelectedRow();
        String dniSelec = String.valueOf(ClientesModelo.getValueAt(celdaSelec, 2));
        Proforma proformaSelec = null;

        iniciarTabla();
        for (Proforma pro : datosCliente) {
            if (dniSelec.equals(pro.getDni())) {
                proformaSelec = pro;
                break;
            }
        }

        if (proformaSelec != null) {
            int opcion = JOptionPane.showOptionDialog(null, "¿Esta seguro?, la acción es irreversible", //contenido de la ventana
                    "Acción importante", //titulo de la ventana
                    JOptionPane.YES_NO_CANCEL_OPTION, //para 3 botones si/no/cancel
                    JOptionPane.QUESTION_MESSAGE, //tipo de ícono
                    (new ImageIcon(getClass().getResource("/imagenesVentanas/logo_coolscooter.png"))), // null para icono por defecto.
                    new Object[]{"Si", "No", "Cancelar"},//objeto para las opciones
                    //null para YES, NO y CANCEL
                    null); //selección predeterminada;  //0 1 2
            if (opcion == 0) {
                datosCliente.remove(proformaSelec);
                try {
                    file.actualizarRegistro(datosCliente);
                    iniciarTabla();
                    iniciarModeloClientes();
                } catch (Exception e) {
                }
            }
        }

    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnEliminarTodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarTodoActionPerformed

        int selecInicio = tabla.getSelectedRow();
        int celdasSelecionadas = tabla.getSelectedRowCount();

        //int opcion = JOptionPane.showConfirmDialog(null, "Se eliminaran " + celdasSelecionadas + " registros de clientes"
        // + "\n¿Esta seguro?, la acción es irreversible");  //0 1 2
        int opcion = JOptionPane.showOptionDialog(null, "Se eliminaran " + celdasSelecionadas + " registros de clientes"
                + "\n¿Esta seguro?, la acción es irreversible", //contenido de la ventana
                "Acción importante", //titulo de la ventana
                JOptionPane.YES_NO_CANCEL_OPTION, //para 3 botones si/no/cancel
                JOptionPane.QUESTION_MESSAGE, //tipo de ícono
                (new ImageIcon(getClass().getResource("/imagenesVentanas/logo_coolscooter.png"))), // null para icono por defecto.
                new Object[]{"Si", "No", "Cancelar"},//objeto para las opciones
                //null para YES, NO y CANCEL
                null); //selección predeterminada

        System.out.println(selecInicio + celdasSelecionadas);
        if (opcion == 0) {
            datosCliente.clear();
            iniciarTabla();
            for (int i = ((selecInicio + celdasSelecionadas) - 1); i >= selecInicio; i--) {
                datosCliente.remove(i);
            }

            try {
                file.actualizarRegistro(datosCliente);
                iniciarTabla();
                iniciarModeloClientes();
            } catch (Exception e) {
            }
        } else {
            //JOptionPane.showMessageDialog(null, "No se seleciono ningun registro");
        }

    }//GEN-LAST:event_btnEliminarTodoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmRepertorioDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmRepertorioDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmRepertorioDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmRepertorioDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmRepertorioDatos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnEliminarTodo;
    private javax.swing.ButtonGroup btngCambioTablasModelo;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lbltituloRepertorio;
    private javax.swing.JMenuItem menuItemCerrarSesión;
    private javax.swing.JMenu menuItemPagWeb;
    private javax.swing.JMenu menuItemPrincipal;
    private javax.swing.JMenu menuItemProforma;
    private javax.swing.JMenu menuItemUser;
    private javax.swing.JTable tabla;
    private javax.swing.JToggleButton tgbCaracteristicas;
    private javax.swing.JToggleButton tgbCaracteristicasFisicas;
    private javax.swing.JToggleButton tgbCliente;
    // End of variables declaration//GEN-END:variables
}
